#spring.application.name=shopapp-api
server:
  port:8080
spring:

  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp_v2"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  resources:
#    static-locations: file:uploads/
#  web:
#    cors:
#      allowed-origins: "http://localhost:4200"
#      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
#      allowed-headers: "Authorization, Content-Type, X-Auth-Token"
#      exposed-headers: "X-Auth-Token"
#  security:
#    filter-dispatcher-types: async, error
#    web:
#      security:
#        filter-chain:
#          - requestMatchers:
#              - "/uploads/**"
#            permitAll: true

api:
  prefix: api/v1

jwt:
  expiration: 259200 #3day 3*24*60*60
  secretKey: R3pOY601wrEKpZb4eWfqK61+MZjbcvq6jRW93BrGkJU=
